#!/bin/bash
#depends ntpdate 
Sntp="time.nist.gov"
sudo ntpdate -s $Sntp && printf "\e[1;32m%-6s\e[m\n" "NTP-date update: done" && nt=1
if [[ $nt = 1 ]];then tput setaf 3 ; tput bold ; echo "NTP-server: $Sntp" ; lock=$(sudo hwclock -u) ; echo "Hardware time: $lock" ; d=$(date); echo "OS time: $d" ;else printf "\e[1;31m%-6s\e[m\n" "ERROR: cant start ntpd" ;fi
tput sgr0
